export const themes = {
  light: {
    '--bg-primary': '#ffffff',
    '--bg-secondary': '#f5f5f7',
    '--bg-tertiary': '#e8e8ed',
    '--bg-canvas': '#fafafa',
    '--bg-node': '#ffffff',
    '--bg-toolbar': '#ffffff',
    '--bg-hover': '#f0f0f5',
    '--bg-active': '#e5e5ea',
    '--bg-modal': '#ffffff',
    '--bg-overlay': 'rgba(0, 0, 0, 0.3)',
    '--text-primary': '#1d1d1f',
    '--text-secondary': '#6e6e73',
    '--text-tertiary': '#aeaeb2',
    '--text-inverse': '#ffffff',
    '--border-primary': '#d2d2d7',
    '--border-secondary': '#e8e8ed',
    '--border-focus': '#0071e3',
    '--accent-blue': '#0071e3',
    '--accent-green': '#34c759',
    '--accent-orange': '#ff9500',
    '--accent-red': '#ff3b30',
    '--accent-purple': '#af52de',
    '--accent-teal': '#5ac8fa',
    '--accent-pink': '#ff2d55',
    '--accent-yellow': '#ffcc00',
    '--shadow-sm': '0 1px 3px rgba(0, 0, 0, 0.08)',
    '--shadow-md': '0 4px 12px rgba(0, 0, 0, 0.1)',
    '--shadow-lg': '0 8px 30px rgba(0, 0, 0, 0.12)',
    '--edge-color': '#8e8e93',
    '--edge-selected': '#0071e3',
    '--minimap-bg': '#f5f5f7',
    '--minimap-mask': 'rgba(0, 0, 0, 0.08)',
  },
  dark: {
    '--bg-primary': '#1c1c1e',
    '--bg-secondary': '#2c2c2e',
    '--bg-tertiary': '#3a3a3c',
    '--bg-canvas': '#141416',
    '--bg-node': '#2c2c2e',
    '--bg-toolbar': '#1c1c1e',
    '--bg-hover': '#3a3a3c',
    '--bg-active': '#48484a',
    '--bg-modal': '#2c2c2e',
    '--bg-overlay': 'rgba(0, 0, 0, 0.5)',
    '--text-primary': '#f5f5f7',
    '--text-secondary': '#aeaeb2',
    '--text-tertiary': '#636366',
    '--text-inverse': '#1d1d1f',
    '--border-primary': '#48484a',
    '--border-secondary': '#3a3a3c',
    '--border-focus': '#0a84ff',
    '--accent-blue': '#0a84ff',
    '--accent-green': '#30d158',
    '--accent-orange': '#ff9f0a',
    '--accent-red': '#ff453a',
    '--accent-purple': '#bf5af2',
    '--accent-teal': '#64d2ff',
    '--accent-pink': '#ff375f',
    '--accent-yellow': '#ffd60a',
    '--shadow-sm': '0 1px 3px rgba(0, 0, 0, 0.3)',
    '--shadow-md': '0 4px 12px rgba(0, 0, 0, 0.4)',
    '--shadow-lg': '0 8px 30px rgba(0, 0, 0, 0.5)',
    '--edge-color': '#636366',
    '--edge-selected': '#0a84ff',
    '--minimap-bg': '#1c1c1e',
    '--minimap-mask': 'rgba(255, 255, 255, 0.06)',
  },
};

export function applyTheme(themeName) {
  const theme = themes[themeName];
  if (!theme) return;
  const root = document.documentElement;
  Object.entries(theme).forEach(([key, value]) => {
    root.style.setProperty(key, value);
  });
  root.setAttribute('data-theme', themeName);
}
